export const countries = [
    { code: "", value: "", continent: "", label: "Select country", mainCities: [] },
    {
        code: "ar",
        value: "argentina",
        label: "Argentina",
        continent: "South America",
        mainCities: [
            { code: "ar-buenos-aires", value: "buenos-aires", label: "Buenos Aires" },
            { code: "ar-cordoba", value: "cordoba", label: "Córdoba" },
            { code: "ar-rosario", value: "rosario", label: "Rosario" },
            { code: "ar-mendoza", value: "mendoza", label: "Mendoza" },
            { code: "ar-bariloche", value: "bariloche", label: "Bariloche" },
        ],
    },
    {
        code: "au",
        value: "australia",
        label: "Australia",
        continent: "Oceania",
        mainCities: [
            { code: "au-sydney", value: "sydney", label: "Sydney" },
            { code: "au-melbourne", value: "melbourne", label: "Melbourne" },
            { code: "au-brisbane", value: "brisbane", label: "Brisbane" },
            { code: "au-perth", value: "perth", label: "Perth" },
            { code: "au-adelaide", value: "adelaide", label: "Adelaide" },
        ],
    },
    {
        code: "br",
        value: "brazil",
        label: "Brazil",
        continent: "South America",
        mainCities: [
            { code: "br-sao-paulo", value: "sao-paulo", label: "São Paulo" },
            { code: "br-rio-de-janeiro", value: "rio-de-janeiro", label: "Rio de Janeiro" },
            { code: "br-brasilia", value: "brasilia", label: "Brasília" },
            { code: "br-salvador", value: "salvador", label: "Salvador" },
            { code: "br-fortaleza", value: "fortaleza", label: "Fortaleza" },
        ],
    },
    {
        code: "ca",
        value: "canada",
        label: "Canada",
        continent: "North America",
        mainCities: [
            { code: "ca-toronto", value: "toronto", label: "Toronto" },
            { code: "ca-montreal", value: "montreal", label: "Montreal" },
            { code: "ca-vancouver", value: "vancouver", label: "Vancouver" },
            { code: "ca-calgary", value: "calgary", label: "Calgary" },
            { code: "ca-ottawa", value: "ottawa", label: "Ottawa" },
        ],
    },
    {
        code: "cn",
        value: "china",
        label: "China",
        continent: "Asia",
        mainCities: [
            { code: "cn-shanghai", value: "shanghai", label: "Shanghai" },
            { code: "cn-beijing", value: "beijing", label: "Beijing" },
            { code: "cn-shenzhen", value: "shenzhen", label: "Shenzhen" },
            { code: "cn-guangzhou", value: "guangzhou", label: "Guangzhou" },
            { code: "cn-xian", value: "xian", label: "Xi'an" },
        ],
    },
    {
        code: "co",
        value: "colombia",
        label: "Colombia",
        continent: "South America",
        mainCities: [
            { code: "co-bogota", value: "bogota", label: "Bogotá" },
            { code: "co-medellin", value: "medellin", label: "Medellín" },
            { code: "co-cali", value: "cali", label: "Cali" },
            { code: "co-cartagena", value: "cartagena", label: "Cartagena" },
            { code: "co-barranquilla", value: "barranquilla", label: "Barranquilla" },
        ],
    },
    {
        code: "eg",
        value: "egypt",
        label: "Egypt",
        continent: "Africa",
        mainCities: [
            { code: "eg-cairo", value: "cairo", label: "Cairo" },
            { code: "eg-alexandria", value: "alexandria", label: "Alexandria" },
            { code: "eg-giza", value: "giza", label: "Giza" },
            { code: "eg-luxor", value: "luxor", label: "Luxor" },
            { code: "eg-aswan", value: "aswan", label: "Aswan" },
        ],
    },
    {
        code: "fr",
        value: "france",
        label: "France",
        continent: "Europe",
        mainCities: [
            { code: "fr-paris", value: "paris", label: "Paris" },
            { code: "fr-marseille", value: "marseille", label: "Marseille" },
            { code: "fr-lyon", value: "lyon", label: "Lyon" },
            { code: "fr-nice", value: "nice", label: "Nice" },
            { code: "fr-bordeaux", value: "bordeaux", label: "Bordeaux" },
        ],
    },
    {
        code: "de",
        value: "germany",
        label: "Germany",
        continent: "Europe",
        mainCities: [
            { code: "de-berlin", value: "berlin", label: "Berlin" },
            { code: "de-hamburg", value: "hamburg", label: "Hamburg" },
            { code: "de-munich", value: "munich", label: "Munich" },
            { code: "de-cologne", value: "cologne", label: "Cologne" },
            { code: "de-frankfurt", value: "frankfurt", label: "Frankfurt" },
        ],
    },
    {
        code: "it",
        value: "italy",
        label: "Italy",
        continent: "Europe",
        mainCities: [
            { code: "it-rome", value: "rome", label: "Rome" },
            { code: "it-milan", value: "milan", label: "Milan" },
            { code: "it-naples", value: "naples", label: "Naples" },
            { code: "it-florence", value: "florence", label: "Florence" },
            { code: "it-venice", value: "venice", label: "Venice" },
        ],
    },
    {
        code: "jp",
        value: "japan",
        label: "Japan",
        continent: "Asia",
        mainCities: [
            { code: "jp-tokyo", value: "tokyo", label: "Tokyo" },
            { code: "jp-osaka", value: "osaka", label: "Osaka" },
            { code: "jp-kyoto", value: "kyoto", label: "Kyoto" },
            { code: "jp-yokohama", value: "yokohama", label: "Yokohama" },
            { code: "jp-sapporo", value: "sapporo", label: "Sapporo" },
        ],
    },
    {
        code: "ke",
        value: "kenya",
        label: "Kenya",
        continent: "Africa",
        mainCities: [
            { code: "ke-nairobi", value: "nairobi", label: "Nairobi" },
            { code: "ke-mombasa", value: "mombasa", label: "Mombasa" },
            { code: "ke-kisumu", value: "kisumu", label: "Kisumu" },
            { code: "ke-nakuru", value: "nakuru", label: "Nakuru" },
            { code: "ke-malindi", value: "malindi", label: "Malindi" },
        ],
    },
    {
        code: "mx",
        value: "mexico",
        label: "Mexico",
        continent: "North America",
        mainCities: [
            { code: "mx-mexico-city", value: "mexico-city", label: "Mexico City" },
            { code: "mx-guadalajara", value: "guadalajara", label: "Guadalajara" },
            { code: "mx-monterrey", value: "monterrey", label: "Monterrey" },
            { code: "mx-cancun", value: "cancun", label: "Cancún" },
            { code: "mx-puebla", value: "puebla", label: "Puebla" },
        ],
    },
    {
        code: "nz",
        value: "new-zealand",
        label: "New Zealand",
        continent: "Oceania",
        mainCities: [
            { code: "nz-auckland", value: "auckland", label: "Auckland" },
            { code: "nz-wellington", value: "wellington", label: "Wellington" },
            { code: "nz-christchurch", value: "christchurch", label: "Christchurch" },
            { code: "nz-queenstown", value: "queenstown", label: "Queenstown" },
            { code: "nz-rotorua", value: "rotorua", label: "Rotorua" },
        ],
    },
    {
        code: "ng",
        value: "nigeria",
        label: "Nigeria",
        continent: "Africa",
        mainCities: [
            { code: "ng-lagos", value: "lagos", label: "Lagos" },
            { code: "ng-abuja", value: "abuja", label: "Abuja" },
            { code: "ng-kano", value: "kano", label: "Kano" },
            { code: "ng-ibadan", value: "ibadan", label: "Ibadan" },
            { code: "ng-port-harcourt", value: "port-harcourt", label: "Port Harcourt" },
        ],
    },
    {
        code: "za",
        value: "south-africa",
        label: "South Africa",
        continent: "Africa",
        mainCities: [
            { code: "za-johannesburg", value: "johannesburg", label: "Johannesburg" },
            { code: "za-cape-town", value: "cape-town", label: "Cape Town" },
            { code: "za-durban", value: "durban", label: "Durban" },
            { code: "za-pretoria", value: "pretoria", label: "Pretoria" },
            { code: "za-gqeberha", value: "gqeberha", label: "Gqeberha" },
        ],
    },
    {
        code: "kr",
        value: "south-korea",
        label: "South Korea",
        continent: "Asia",
        mainCities: [
            { code: "kr-seoul", value: "seoul", label: "Seoul" },
            { code: "kr-busan", value: "busan", label: "Busan" },
            { code: "kr-incheon", value: "incheon", label: "Incheon" },
            { code: "kr-daegu", value: "daegu", label: "Daegu" },
            { code: "kr-jeju-city", value: "jeju-city", label: "Jeju City" },
        ],
    },
    {
        code: "gb",
        value: "united-kingdom",
        label: "United Kingdom",
        continent: "Europe",
        mainCities: [
            { code: "gb-london", value: "london", label: "London" },
            { code: "gb-edinburgh", value: "edinburgh", label: "Edinburgh" },
            { code: "gb-manchester", value: "manchester", label: "Manchester" },
            { code: "gb-birmingham", value: "birmingham", label: "Birmingham" },
            { code: "gb-glasgow", value: "glasgow", label: "Glasgow" },
        ],
    },
    {
        code: "us",
        value: "united-states",
        label: "United States",
        continent: "North America",
        mainCities: [
            { code: "us-new-york-city", value: "new-york-city", label: "New York City" },
            { code: "us-los-angeles", value: "los-angeles", label: "Los Angeles" },
            { code: "us-chicago", value: "chicago", label: "Chicago" },
            { code: "us-san-francisco", value: "san-francisco", label: "San Francisco" },
            { code: "us-las-vegas", value: "las-vegas", label: "Las Vegas" },
        ],
    },
]

export type Country = (typeof countries)[number]
export type City = Country["mainCities"][number]
